[package]
name = "ttf2mesh_triangulation"
version = "0.1.0"
edition = "2021"

[dependencies]
snafu = "0.7"

[dev-dependencies]
byteorder = "1.4"
macroquad = "0.3"
ttf-parser = "0.18"

[features]
default = []
original_algorithm = []
